In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import dalmatian
import re
import numpy as np

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.
Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.

## Retrieving MAFs using dalmatian

Loading protected data from Terra workspace.

In [2]:
wm = dalmatian.WorkspaceManager('rjendometrial/CDK46')
samples = wm.get_pairs()
sample_sets = wm.get_sample_sets()
participants = wm.get_participants()
samples

/Users/kprasad/opt/anaconda3/envs/CDK46/lib/python3.9/site-packages/google/auth/_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

,picard_PCT_TARGET_BASES_50X,case_sample,picard_MEDIAN_INSERT_SIZE,picard_PCT_EXC_OFF_TARGET,picard_MEDIAN_ABSOLUTE_DEVIATION,picard_TOTAL_READS,picard_MEDIAN_TARGET_COVERAGE,participant,picard_PCT_PF_READS_IMPROPER_PAIRS,picard_PF_HQ_ERROR_RATE,...,deTiN_aSCNA_model,ffpe_OBF_passed_and_rejected_mutations,all_filters_passed_merged_maf,num_passed_mutations,partial_mafs,blat_pass_maf,passMaf,allMaf,num_rejected_mutations,debug_results
pair_id,,,,,,,,,,,,,,,,,,,,,
CKDN190050174-1A_CKDN190050174-1A,0.499159,CKDN190050174-1A,241,0.58511,41,60748130,49,Basal,60748130\n1,0.00215,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001812-1A_CKDN190050174-1A,0.731329,CKDN200001812-1A,237,0.543073,41,109506058,84,DOXDMSO3_2,109506058\n1,0.001675,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001814-1A_CKDN190050174-1A,0.842373,CKDN200001814-1A,258,0.563901,50,153573378,122,DOXDMSO3_6,153573378\n1,0.001714,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001815-1A_CKDN190050174-1A,0.799939,CKDN200001815-1A,238,0.533675,40,129040318,102,DOXDMSO3_7,129040318\n1,0.001689,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001816-1A_CKDN190050174-1A,0.012112,CKDN200001816-1A,189,0.527526,64,16809198,8,DOXDMSO3_9,16809198\n1,0.002967,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001817-1A_CKDN190050174-1A,0.795048,CKDN200001817-1A,264,0.5701,52,161652212,117,NDPR3_1,161652212\n1,0.001829,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001818-1A_CKDN190050174-1A,0.546828,CKDN200001818-1A,255,0.594707,49,100077878,58,NDPR3_2,100077878\n1,0.002137,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001819-1A_CKDN190050174-1A,0.6788,CKDN200001819-1A,274,0.601126,57,117517002,84,NDPR3_15,117517002\n1,0.002025,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001820-1A_CKDN190050174-1A,0.092413,CKDN200001820-1A,247,0.646657,49,16867312,10,DOXPR3_1,16867312\n1,0.002711,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200001821-1A_CKDN190050174-1A,0.653402,CKDN200001821-1A,278,0.668926,56,105358624,75,DOXPR3_2,105358624\n1,0.002334,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200002460-1A_CKDN190050174-1A,0.601526,CKDN200002460-1A,244,0.559057,46,87942640,60,NDDMSO3_2,87942640\n1,0.002093,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200002461-1A_CKDN190050174-1A,0.325603,CKDN200002461-1A,207,0.502931,35,48023526,35,NDDMSO3_5,48023526\n1,0.003971,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200002462-1A_CKDN190050174-1A,0.402104,CKDN200002462-1A,241,0.570471,46,69846478,42,NDDMSO3_6,69846478\n1,0.00265,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200002463-1A_CKDN190050174-1A,0.611141,CKDN200002463-1A,237,0.550593,44,86678262,63,NDDMSO3_7,86678262\n1,0.002262,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200002464-1A_CKDN190050174-1A,0.529486,CKDN200002464-1A,238,0.561556,44,67107882,52,DOXDMSO3_3,67107882\n1,0.002485,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004562-1A_CKDN190050174-1A,0.769638,CKDN200004562-1A,279,0.641903,55,115739334,97,NDABR_1,115739334\n1,0.002496,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004563-1A_CKDN190050174-1A,0.747337,CKDN200004563-1A,285,0.644982,58,116811096,94,NDABR_2,116811096\n1,0.002493,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004564-1A_CKDN190050174-1A,0.739348,CKDN200004564-1A,273,0.655811,53,100445256,87,NDABR_3,100445256\n1,0.00246,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004818-1A_CKDN190050174-1A,0.726657,CKDN200004818-1A,241,0.586785,41,94671514,80,DXABR_1,94671514\n1,0.002262,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004819-1A_CKDN190050174-1A,0.725426,CKDN200004819-1A,243,0.577586,41,97319288,79,DXABR_2,97319288\n1,0.002529,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004820-1A_CKDN190050174-1A,0.835337,CKDN200004820-1A,248,0.537644,44,146399964,113,DXABR_3,146399964\n1,0.002011,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004900-1A_CKDN190050174-1A,0.013909,CKDN200004900-1A,276,0.646016,50,13511310,13,MCF10,13511310\n1,0.001972,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004901-1A_CKDN190050174-1A,0.009343,CKDN200004901-1A,272,0.641499,49,12978930,13,HMEC_1,12978930\n1,0.001829,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200004902-1A_CKDN190050174-1A,0.003855,CKDN200004902-1A,273,0.660022,51,11123102,11,HMEC_2,11123102\n1,0.00198,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005468-1A_CKDN190050174-1A,,CKDN200005468-1A,,,,,,M814PL,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005470-1A_CKDN190050174-1A,,CKDN200005470-1A,,,,,,M814LIMT,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005470-1A_CKDN200005468-1A,,CKDN200005470-1A,,,,,,M814LIMT,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005472-1A_CKDN190050174-1A,,CKDN200005472-1A,,,,,,M816REC1,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005472-1A_CKDN200005589-1A,,CKDN200005472-1A,,,,,,M816REC1,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,84.0,[gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,[gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/...,[gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/...,1.0,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200005473-1A_CKDN190050174-1A,,CKDN200005473-1A,,,,,,M817PL,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005474-1A_CKDN190050174-1A,,CKDN200005474-1A,,,,,,M817REC1,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005474-1A_CKDN200005473-1A,,CKDN200005474-1A,,,,,,M817REC1,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005475-1A_CKDN190050174-1A,,CKDN200005475-1A,,,,,,M817SPMT,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005476-1A_CKDN190050174-1A,,CKDN200005476-1A,,,,,,M825PL,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005477-1A_CKDN190050174-1A,,CKDN200005477-1A,,,,,,M825SPMT,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005478-1A_CKDN190050174-1A,,CKDN200005478-1A,,,,,,M825LIMT,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005478-1A_CKDN200005476-1A,,CKDN200005478-1A,,,,,,M825LIMT,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005588-1A_CKDN190050174-1A,,CKDN200005588-1A,,,,,,M814SPMT,,,...,,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN
CKDN200005589-1A_CKDN190050174-1A,,CKDN200005589-1A,,,,,,M816PE,,,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091271_CKDN190050174-1A,0.091793,USD16091271,254,0.685552,49,17928394,14,NDDMSO1,17928394\n1,0.002356,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091272_CKDN190050174-1A,0.248678,USD16091272,243,0.732885,42,28780122,27,NDDMSO2,28780122\n1,0.001839,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091274_CKDN190050174-1A,0.009572,USD16091274,241,0.659382,40,8926420,8,NDPDR1,8926420\n1,0.00206,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091277_CKDN190050174-1A,0.621691,USD16091277,245,0.619644,41,81327980,65,DOXDMSO1,81327980\n1,0.002254,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091279_CKDN190050174-1A,0.119019,USD16091279,239,0.71777,40,20185010,19,DOXDMSO3,20185010\n1,0.001983,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091280_CKDN190050174-1A,0.012881,USD16091280,234,0.659592,39,8996690,8,DOXPDR1,8996690\n1,0.001996,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091282_CKDN190050174-1A,0.018561,USD16091282,233,0.698271,38,9116424,8,DOXPDR3,9116424\n1,0.001875,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091450_CKDN190050174-1A,0.772496,USD16091450,231,0.670775,37,106880932,98,NDDMSO3,106880932\n1,0.002019,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091451_CKDN190050174-1A,0.330574,USD16091451,240,0.677668,37,37145914,35,NDPDR2,37145914\n1,0.001618,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091453_CKDN190050174-1A,0.335797,USD16091453,236,0.670184,37,37292106,36,DOXDMSO2,37292106\n1,0.001611,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091454_CKDN190050174-1A,0.215656,USD16091454,244,0.689312,44,28082368,25,DOXPDR2,28082368\n1,0.001798,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
USD16091488_CKDN190050174-1A,0.118404,USD16091488,261,0.589599,49,23943880,16,NDPDR3,23943880\n1,0.002131,...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
samples_of_interest = ["USD16091271_CKDN190050174-1A", "USD16091272_CKDN190050174-1A", #Bulk - Palbo
                      "USD16091274_CKDN190050174-1A", "USD16091277_CKDN190050174-1A", #Bulk - Palbo
                      "USD16091279_CKDN190050174-1A", "USD16091280_CKDN190050174-1A",#Bulk - Palbo
                      "USD16091282_CKDN190050174-1A", "USD16091450_CKDN190050174-1A",#Bulk - Palbo
                      "USD16091451_CKDN190050174-1A", "USD16091453_CKDN190050174-1A",#Bulk - Palbo
                      "USD16091454_CKDN190050174-1A", "USD16091488_CKDN190050174-1A",#Bulk - Palbo
                      "CKDN200004562-1A_CKDN190050174-1A", "CKDN200004563-1A_CKDN190050174-1A",#Bulk - Abema
                      "CKDN200004564-1A_CKDN190050174-1A", "CKDN200004818-1A_CKDN190050174-1A",#Bulk - Abema
                      "CKDN200004819-1A_CKDN190050174-1A", 'CKDN200004820-1A_CKDN190050174-1A',#Bulk - Abema
                      "CKDN200002461-1A_CKDN190050174-1A", "CKDN200002463-1A_CKDN190050174-1A",# CL WT Vehicle
                      "CKDN200001814-1A_CKDN190050174-1A","CKDN200001816-1A_CKDN190050174-1A",# CL Mut Vehicle
                      "CKDN200001817-1A_CKDN190050174-1A","CKDN200001819-1A_CKDN190050174-1A",# CL WT PalboR
                      "CKDN200001820-1A_CKDN190050174-1A","CKDN200001821-1A_CKDN190050174-1A"] # CL Mut PalboR

In [4]:
maf_paths = samples.loc[samples_of_interest, 'mutation_validator_validated_maf']

In [5]:
maf_paths.index = maf_paths.index.to_series().str.split("_").str[0]
maf_paths

pair_id
USD16091271         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091272         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091274         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091277         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091279         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091280         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091282         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091450         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091451         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091453         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091454         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
USD16091488         gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004562-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004563-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004564-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004818-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004819-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200004820-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200002461-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200002463-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001814-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001816-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001817-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001819-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001820-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
CKDN200001821-1A    gs://fc-ecacb4b2-f185-4e48-a03a-dae1abd81260/s...
Name: mutation_validator_validated_maf, dtype: object

In [6]:
cur_name_to_new_name_lut = {'CKDN200001812-1A': 'DOXDMSO3_2_CKDN200001812', 'USD16091280': 'DOXPDR1_USD16091280',
                            'CKDN200004562-1A': 'NDABR_1_CKDN200004562', 'CKDN200001818-1A': 'NDPR3_2_CKDN200001818',
                            'CKDN200001815-1A': 'DOXDMSO3_7_CKDN200001815', 'CKDN200001819-1A': 'NDPR3_15_CKDN200001819',
                            'CKDN200004818-1A': 'DXABR_1_CKDN200004818', 'CKDN200002463-1A': 'NDDMSO3_7_CKDN200002463',
                            'CKDN200004820-1A': 'DXABR_3_CKDN200004820', 'USD16091454': 'DOXPDR2_USD16091454',
                            'CKDN200004563-1A': 'NDABR_2_CKDN200004563', 'CKDN200002461-1A': 'NDDMSO3_5_CKDN200002461',
                            'CKDN200001817-1A': 'NDPR3_1_CKDN200001817', 'USD16091272': 'NDDMSO2_USD16091272',
                            'USD16091453': 'DOXDMSO2_USD16091453', 'USD16091488': 'NDPDR3_USD16091488',
                            'USD16091282': 'DOXPDR3_USD16091282', 'USD16091274': 'NDPDR1_USD16091274',
                            'CKDN200002460-1A': 'NDDMSO3_2_CKDN200002460', 'CKDN200001820-1A': 'DOXPR3_1_CKDN200001820',
                            'CKDN200001821-1A': 'DOXPR3_2_CKDN200001821', 'CKDN200001816-1A': 'DOXDMSO3_9_CKDN200001816',
                            'CKDN190050174-1A': 'Basal_CKDN190050174', 'USD16091271': 'NDDMSO1_USD16091271',
                            'USD16091277': 'DOXDMSO1_USD16091277', 'USD16091450': 'NDDMSO3_USD16091450',
                            'CKDN200002462-1A': 'NDDMSO3_6_CKDN200002462', 'USD16091451': 'NDPDR2_USD16091451',
                            'CKDN200002464-1A': 'DOXDMSO3_3_CKDN200002464', 'CKDN200004819-1A': 'DXABR_2_CKDN200004819',
                            'USD16091279': 'DOXDMSO3_USD16091279', 'CKDN200001814-1A': 'DOXDMSO3_6_CKDN200001814',
                            'CKDN200004564-1A': 'NDABR_3_CKDN200004564'}
cur_name_to_new_name_lut_subset = {k:v for k,v in cur_name_to_new_name_lut.items() if k in maf_paths.index}
cur_name_to_new_name_lut_subset

{'USD16091280': 'DOXPDR1_USD16091280',
 'CKDN200004562-1A': 'NDABR_1_CKDN200004562',
 'CKDN200001819-1A': 'NDPR3_15_CKDN200001819',
 'CKDN200004818-1A': 'DXABR_1_CKDN200004818',
 'CKDN200002463-1A': 'NDDMSO3_7_CKDN200002463',
 'CKDN200004820-1A': 'DXABR_3_CKDN200004820',
 'USD16091454': 'DOXPDR2_USD16091454',
 'CKDN200004563-1A': 'NDABR_2_CKDN200004563',
 'CKDN200002461-1A': 'NDDMSO3_5_CKDN200002461',
 'CKDN200001817-1A': 'NDPR3_1_CKDN200001817',
 'USD16091272': 'NDDMSO2_USD16091272',
 'USD16091453': 'DOXDMSO2_USD16091453',
 'USD16091488': 'NDPDR3_USD16091488',
 'USD16091282': 'DOXPDR3_USD16091282',
 'USD16091274': 'NDPDR1_USD16091274',
 'CKDN200001820-1A': 'DOXPR3_1_CKDN200001820',
 'CKDN200001821-1A': 'DOXPR3_2_CKDN200001821',
 'CKDN200001816-1A': 'DOXDMSO3_9_CKDN200001816',
 'USD16091271': 'NDDMSO1_USD16091271',
 'USD16091277': 'DOXDMSO1_USD16091277',
 'USD16091450': 'NDDMSO3_USD16091450',
 'USD16091451': 'NDPDR2_USD16091451',
 'CKDN200004819-1A': 'DXABR_2_CKDN200004819',
 'USD16091279': 'DOXDMSO3_USD16091279',
 'CKDN200001814-1A': 'DOXDMSO3_6_CKDN200001814',
 'CKDN200004564-1A': 'NDABR_3_CKDN200004564'}

In [7]:
# Have all samples of interest received a mapping?
assert len(cur_name_to_new_name_lut_subset) == len(samples_of_interest)

Get all somatic mutations across all samples and keep only the required information about each of them.

In [8]:
keep_cols = ['Hugo_Symbol',
 'Chromosome',
 'Start_position',
 'End_position',
 'Strand',
 'Variant_Classification',
 'Variant_Type',
 'Reference_Allele',
 'Tumor_Seq_Allele1',
 'Tumor_Seq_Allele2',
 'Tumor_Sample_Barcode',
 't_alt_count',
 't_ref_count',
 'Genome_Change',
 'Protein_Change',
 'ESP_MAF']

In [9]:
combined_maf_df = pd.DataFrame()
for maf in maf_paths:
    sample_maf = pd.read_csv(maf, sep = "\t", header = 0)
    combined_maf_df = pd.concat([combined_maf_df, sample_maf.loc[:, keep_cols]], ignore_index = True)


display(combined_maf_df)

/Users/kprasad/opt/anaconda3/envs/CDK46/lib/python3.9/site-packages/google/auth/_default.py:78: UserWarning: Your application has authenticated using end user credentials from Google Cloud SDK without a quota project. You might receive a "quota exceeded" or "API not enabled" error. See the following page for troubleshooting: https://cloud.google.com/docs/authentication/adc-troubleshooting/user-creds.
  warnings.warn(_CLOUD_SDK_CREDENTIALS_WARNING)

,Hugo_Symbol,Chromosome,Start_position,End_position,Strand,Variant_Classification,Variant_Type,Reference_Allele,Tumor_Seq_Allele1,Tumor_Seq_Allele2,Tumor_Sample_Barcode,t_alt_count,t_ref_count,Genome_Change,Protein_Change,ESP_MAF
0,SRRM1,1,24989227,24989227,__UNKNOWN__,Silent,SNP,G,G,A,USD16091271,4,1,g.chr1:24989227G>A,p.R520R,NaN
1,FUT11,10,75532979,75532979,__UNKNOWN__,Missense_Mutation,SNP,G,G,T,USD16091271,3,31,g.chr10:75532979G>T,p.R247L,NaN
2,CCDC64B,16,3080799,3080799,__UNKNOWN__,Silent,SNP,C,C,T,USD16091271,10,19,g.chr16:3080799C>T,p.E171E,NaN
3,C16orf58,16,31503398,31503398,__UNKNOWN__,Missense_Mutation,SNP,T,T,C,USD16091271,3,35,g.chr16:31503398T>C,p.K414R,NaN
4,CBX8,17,77768657,77768657,__UNKNOWN__,Missense_Mutation,SNP,G,G,T,USD16091271,12,30,g.chr17:77768657G>T,p.S316Y,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1419,FAM186A,12,50745987,50746022,__UNKNOWN__,In_Frame_Del,DEL,AGAGGGATCCCCAATTCCTGAGCCTGCGGAGGGATC,AGAGGGATCCCCAATTCCTGAGCCTGCGGAGGGATC,-,CKDN200001821-1A,15,114,g.chr12:50745987_50746022delAGAGGGATCCCCAATTCC...,p.1531_1543LIPPQAQELGIPL>L,NaN
1420,PRKCH,14,61924086,61924092,__UNKNOWN__,Intron,DEL,ATGGGGG,ATGGGGG,-,CKDN200001821-1A,4,112,g.chr14:61924086_61924092delATGGGGG,NaN,NaN
1421,UNK,17,73816181,73816182,__UNKNOWN__,Frame_Shift_Ins,INS,-,-,GAACCTCAGC,CKDN200001821-1A,47,617,g.chr17:73816181_73816182insGAACCTCAGC,p.S611fs,NaN
1422,USE1,19,17328216,17328217,__UNKNOWN__,Intron,INS,-,-,TTACAGGC,CKDN200001821-1A,4,83,g.chr19:17328216_17328217insTTACAGGC,NaN,NaN
1423,NLGN4X,X,5821231,5821231,__UNKNOWN__,Frame_Shift_Del,DEL,G,G,-,CKDN200001821-1A,76,63,g.chrX:5821231delG,p.V496fs,NaN

In [10]:
combined_maf_df['Gene_Site'] = combined_maf_df['Hugo_Symbol'] + ":" + combined_maf_df['Genome_Change']

Obtain all those mutations that are recurrent (defined as present in at least 2 samples), but still have some variability in mutational status across samples (defined as present in upto 24 out of 26 samples). These are likely to best help differentiate samples into biologically meaningful clusters.

In [11]:
combined_maf_df_val_count = pd.DataFrame(combined_maf_df['Gene_Site'].value_counts())
combined_maf_df_val_count.head()

combined_maf_df_val_count_subset = combined_maf_df_val_count.loc[combined_maf_df_val_count['Gene_Site'] >= 2]
combined_maf_df_val_count_subset = combined_maf_df_val_count_subset.loc[combined_maf_df_val_count_subset['Gene_Site'] <= 24]

In [12]:
shortlisted_gene_sites = list(combined_maf_df_val_count_subset.index)

combined_maf_df_subset = combined_maf_df.loc[combined_maf_df.iloc[:, -1].isin(shortlisted_gene_sites)]

In [13]:
# Reordering some columns

gene_site_col = combined_maf_df_subset.pop('Gene_Site')
combined_maf_df_subset.insert(0, 'Gene_Site', gene_site_col)

# Renaming some columns based on what OncoKB's annotation API likes

combined_maf_df_subset = combined_maf_df_subset.rename(columns={"Gene_Site": "Hugo_Symbol", "Hugo_Symbol": "Gene",
                                                               "Protein_Change":"HGVSP_SHORT"})

# Calculating Variant Allele Fraction (VAF) for all mutations

combined_maf_df_subset["tumor_f"] = combined_maf_df_subset["t_alt_count"]/(combined_maf_df_subset["t_alt_count"] + combined_maf_df_subset["t_ref_count"])

Keeping just those mutations that are the least likely to be germline (VAF in Exome Sequencing Project (ESP) database is less than 10%, or mutation is absent there).

In [14]:
combined_maf_df_ESP_MAF = combined_maf_df_subset['ESP_MAF']

# In case of multiple population frequencies, keep just the maximum value
for i in range(len(combined_maf_df_ESP_MAF.index)):
    x = combined_maf_df_ESP_MAF.iloc[i]
    if type(x) == str:
        x_split = x.split(",")
        x_split = [float(y) for y in x_split]
        x_max = max(x_split)
        combined_maf_df_ESP_MAF.iloc[i] = x_max

combined_maf_df_ESP_MAF_subset = combined_maf_df_ESP_MAF[(combined_maf_df_ESP_MAF < 0.1) | (combined_maf_df_ESP_MAF.isna())]
combined_maf_df_subset = combined_maf_df_subset.loc[combined_maf_df_ESP_MAF_subset.index]

/var/folders/q_/j_57k8z50v17pvnyw6788yc00000gq/T/ipykernel_28958/708715082.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  combined_maf_df_ESP_MAF.iloc[i] = x_max

### Annotating cancer genes

Indicate which genes are from COSMIC's Cancer Gene Census by preparing an annotation file.

In [15]:
cgc_df = pd.read_csv("Census_allFri Jan 10 21_14_42 2025.tsv", sep = "\t", header = 0)

In [16]:
combined_maf_df_subset["CancerGene"] = combined_maf_df_subset['Gene'].isin(cgc_df['Gene Symbol']).map({True: 'Yes', False: 'No'})

In [17]:
combined_maf_df_subset[["Hugo_Symbol", "CancerGene"]].to_csv("CDK46_barcoding_CoMut_cgc_anno.tsv", sep = "\t", index = False)

In [18]:
# Renaming columns back to preferred way
combined_maf_df_subset = combined_maf_df_subset.rename(columns={"Hugo_Symbol":"Gene_Site",  "Gene":"Hugo_Symbol"})

In [19]:
combined_maf_df_subset.to_csv("CDK46_barcoding_CoMut_maf.maf", sep = "\t", index = False)

### Annotating pathogenicity

Preparing an annotation file for pathogenicity from OncoKB's outputs.

In [20]:
combined_maf_df_subset_anno = pd.read_csv("CDK46_barcoding_CoMut_OncoKB_maf.maf", sep = "\t", header = 0)
combined_maf_df_subset_anno = combined_maf_df_subset_anno.rename(columns={"Gene_Site":"Hugo_Symbol",  "Hugo_Symbol":"Gene"})

In [21]:
combined_maf_df_subset_anno[["Hugo_Symbol", "MUTATION_EFFECT"]].to_csv("CDK46_barcoding_CoMut_patho_anno.tsv", sep = "\t", index = False)

In [22]:
combined_maf_df_subset_anno.to_csv("CDK46_barcoding_CoMut_maf.maf", sep = "\t", index = False)

In [23]:
#combined_maf_df_subset_anno[["Hugo_Symbol", "Chromosome"]].to_csv("CDK46_barcoding_CoMut_chr_anno.tsv", sep = "\t", index = False)